import { frontends } from '../registry/frontends.js';

/**
 * Generate .env.example and .env content based on the chosen frontend and database.
 *
 * .env.example  – committed to git, shows required variables with placeholder values
 * .env          – gitignored, pre-filled with safe local defaults so `docker compose up`
 *                 works out of the box without any extra setup
 *
 * @param {{ frontend: string, database: string }} options
 * @returns {{ envExample: string, envLocal: string }}
 */
export function generateEnv({ frontend, database }) {
  const frontendMeta = frontends.find((f) => f.id === frontend);

  const lines = [
    '# ─────────────────────────────────────────────',
    '# Generated by create-allthing',
    '# Copy this file to .env and fill in real values',
    '# ─────────────────────────────────────────────',
    '',
  ];

  // Only add frontend build arg env var when the frontend uses one (e.g. Vite)
  if (frontendMeta?.buildArg) {
    lines.push('# Frontend', `${frontendMeta.buildArg}=http://localhost:8080`, '');
  }

  const localLines = [...lines];

  if (database === 'postgres') {
    const dbSection = [
      '# PostgreSQL',
      'POSTGRES_USER=appuser',
      'POSTGRES_PASSWORD=changeme',
      'POSTGRES_DB=appdb',
      'DATABASE_URL=postgresql://appuser:changeme@db:5432/appdb',
      '',
    ];

    const exampleDbSection = [
      '# PostgreSQL',
      'POSTGRES_USER=appuser',
      'POSTGRES_PASSWORD=<your-strong-password>',
      'POSTGRES_DB=appdb',
      'DATABASE_URL=postgresql://appuser:<your-strong-password>@db:5432/appdb',
      '',
    ];

    lines.push(...exampleDbSection);
    localLines.push(...dbSection);
  } else if (database === 'mongodb') {
    const dbSection = [
      '# MongoDB',
      'MONGO_INITDB_ROOT_USERNAME=appuser',
      'MONGO_INITDB_ROOT_PASSWORD=changeme',
      'MONGO_INITDB_DATABASE=appdb',
      'MONGODB_URL=mongodb://appuser:changeme@db:27017/appdb?authSource=admin',
      '',
    ];

    const exampleDbSection = [
      '# MongoDB',
      'MONGO_INITDB_ROOT_USERNAME=appuser',
      'MONGO_INITDB_ROOT_PASSWORD=<your-strong-password>',
      'MONGO_INITDB_DATABASE=appdb',
      'MONGODB_URL=mongodb://appuser:<your-strong-password>@db:27017/appdb?authSource=admin',
      '',
    ];

    lines.push(...exampleDbSection);
    localLines.push(...dbSection);
  }

  // Shared optional vars
  const sharedSection = [
    '# App',
    'NODE_ENV=development',
    'LOG_LEVEL=info',
    '',
  ];

  lines.push(...sharedSection);
  localLines.push(...sharedSection);

  return {
    envExample: lines.join('\n'),
    envLocal: localLines.join('\n'),
  };
}
