import { frontends } from '../registry/frontends.js';
import { backends } from '../registry/backends.js';

/**
 * Generate a Jenkinsfile with a multi-environment pipeline (dev → staging → prod).
 *
 * @param {{ frontend: string, backend: string, database: string }} options
 * @returns {string}
 */
export function generateJenkinsfile({ frontend, backend, database }) {
  const frontendMeta = frontends.find((f) => f.id === frontend);
  const backendMeta = backends.find((b) => b.id === backend);

  // ── Frontend build command ──────────────────────────────────────────────
  const frontendBuild = frontend === 'angular'
    ? 'npm ci && npm run build -- --configuration production'
    : 'npm ci && npm run build';

  // ── Backend build & test commands ───────────────────────────────────────
  let backendBuild;
  let backendTest;
  if (backend === 'fastapi') {
    backendBuild = 'pip install uv && uv sync';
    backendTest = 'uv run pytest';
  } else if (backend === 'dotnet') {
    backendBuild = 'dotnet restore && dotnet build';
    backendTest = 'dotnet test';
  } else {
    backendBuild = 'echo "Build step not configured"';
    backendTest = 'echo "Test step not configured"';
  }

  // ── Environment variables ───────────────────────────────────────────────
  const envVars = [];
  if (database === 'postgres') {
    envVars.push(
      "POSTGRES_USER     = credentials('db-credentials').username",
      "POSTGRES_PASSWORD  = credentials('db-credentials').password",
      "POSTGRES_DB        = 'appdb'",
    );
  } else if (database === 'mongodb') {
    envVars.push(
      "MONGO_INITDB_ROOT_USERNAME = credentials('db-credentials').username",
      "MONGO_INITDB_ROOT_PASSWORD = credentials('db-credentials').password",
      "MONGO_INITDB_DATABASE      = 'appdb'",
    );
  }

  const envBlock = envVars.length > 0
    ? `\n    environment {\n        ${envVars.join('\n        ')}\n    }\n`
    : '';

  return `// Generated by create-allthing
// Declarative pipeline: dev → staging → prod with manual approval

pipeline {
    agent any
${envBlock}
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Frontend') {
            steps {
                dir('frontend') {
                    sh '${frontendBuild}'
                }
            }
        }

        stage('Build Backend') {
            steps {
                dir('backend') {
                    sh '${backendBuild}'
                }
            }
        }

        stage('Test Backend') {
            steps {
                dir('backend') {
                    sh '${backendTest}'
                }
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker compose build'
            }
        }

        stage('Deploy to Dev') {
            steps {
                echo 'Deploying to dev environment...'
                sh '''
                    docker compose -f docker-compose.yml \\
                        --project-name dev \\
                        up -d --build
                '''
            }
        }

        stage('Deploy to Staging') {
            steps {
                echo 'Deploying to staging environment...'
                sh '''
                    docker compose -f docker-compose.yml \\
                        --project-name staging \\
                        up -d --build
                '''
            }
        }

        stage('Deploy to Prod') {
            when {
                branch 'main'
            }
            input {
                message 'Approve deploy to production?'
                ok 'Deploy'
            }
            steps {
                echo 'Deploying to production...'
                sh '''
                    docker compose -f docker-compose.yml \\
                        --project-name prod \\
                        up -d --build
                '''
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished.'
        }
        failure {
            echo 'Pipeline failed — check the logs above.'
        }
        success {
            echo 'Pipeline completed successfully.'
        }
    }
}
`;
}
