import { frontends } from '../registry/frontends.js';
import { backends } from '../registry/backends.js';
import { databases } from '../registry/databases.js';

/**
 * Generate README.md content.
 *
 * @param {{ projectName: string, frontend: string, backend: string, database: string }} options
 * @returns {string}
 */
export function generateReadme({ projectName, frontend, backend, database }) {
  const frontendMeta = frontends.find((f) => f.id === frontend);
  const backendMeta = backends.find((b) => b.id === backend);
  const dbMeta = databases.find((d) => d.id === database);
  const hasDb = database !== 'none' && dbMeta != null;

  const frontendLabel = frontendMeta?.label ?? frontend;
  const backendLabel = backendMeta?.label ?? backend;
  const dbLabel = dbMeta?.label ?? database;
  const testCmd = backendMeta?.readmeTest ?? 'cd backend && <run tests>';

  const dbSetupSection = hasDb
    ? `\n### Database\n\nCopy the example env file and adjust the credentials:\n\n\`\`\`bash\ncp .env.example .env\n# Edit .env — change passwords before going to production!\n\`\`\`\n`
    : '';

  const dbPortSection = hasDb
    ? `| ${dbLabel} | \`localhost:${dbMeta.port}\` |\n`
    : '';

  const dbEnvSection =
    database === 'postgres'
      ? `| \`DATABASE_URL\` | PostgreSQL connection string |\n| \`POSTGRES_USER\` | DB username |\n| \`POSTGRES_PASSWORD\` | DB password |\n| \`POSTGRES_DB\` | Database name |`
      : database === 'mongodb'
      ? `| \`MONGODB_URL\` | MongoDB connection string |\n| \`MONGO_INITDB_ROOT_USERNAME\` | DB username |\n| \`MONGO_INITDB_ROOT_PASSWORD\` | DB password |\n| \`MONGO_INITDB_DATABASE\` | Database name |`
      : '_No database configured._';

  return `# ${projectName}

> Scaffolded with [create-allthing](https://github.com/your-org/create-allthing)

## Stack

| Layer    | Technology      |
|----------|----------------|
| Frontend | ${frontendLabel} |
| Backend  | ${backendLabel} |
| Database | ${dbLabel}      |
| Runtime  | Docker Compose  |

## Quick start

\`\`\`bash
# 1. Clone / enter the project
cd ${projectName}
${hasDb ? '\n# 2. Set up environment\ncp .env.example .env\n# Edit .env with your credentials\n' : ''}
# ${hasDb ? '3' : '2'}. Start all services
docker compose up --build
\`\`\`

Services will be available at:

| Service  | URL |
|----------|-----|
| Frontend | <http://localhost:3000> |
| Backend  | <http://localhost:8080> |
| API docs | <http://localhost:8080/docs> |
${dbPortSection}
## Development
${dbSetupSection}
### Frontend

\`\`\`bash
${frontendMeta?.readmeDev ?? 'cd frontend\nnpm install\nnpm run dev'}
\`\`\`

### Backend

${
  backend === 'fastapi'
    ? `\`\`\`bash
cd backend
uv sync         # install dependencies into .venv
uv run uvicorn src.main:app --reload --port 8080
\`\`\``
    : `\`\`\`bash
cd backend
dotnet restore
dotnet run      # http://localhost:8080
\`\`\``
}

## Testing

\`\`\`bash
${testCmd}
\`\`\`

## Environment variables

| Variable | Description |
|----------|-------------|
${frontendMeta?.buildArg ? `| \`${frontendMeta.buildArg}\` | Backend URL used by the frontend build |` : ''}
${dbEnvSection}

## Docker commands

\`\`\`bash
# Start in background
docker compose up -d --build

# Follow logs
docker compose logs -f

# Stop everything (keep volumes)
docker compose down

# Stop and remove volumes (wipe database)
docker compose down -v

# Rebuild a single service
docker compose up --build frontend
\`\`\`

## Project structure

\`\`\`
${projectName}/
├── frontend/           ${frontendLabel} SPA
│   ├── src/
│   ├── Dockerfile
│   └── nginx.conf
├── backend/            ${backendLabel} API
│   ├── ${backend === 'fastapi' ? 'src/' : 'Controllers/'}
│   └── Dockerfile
├── infra/
│   ├── scripts/        Helper shell scripts
│   └── db/             Migrations & seeds
├── mcp/                Model Context Protocol tools
├── docs/
│   ├── specs/          Feature specifications
│   └── agents.md       AI agent instructions
├── .claude/            AI skill configurations
├── docker-compose.yml
├── .env.example
└── README.md           ← you are here
\`\`\`

## Contributing

1. Create a feature branch: \`git checkout -b feat/my-feature\`
2. Make your changes
3. Run tests: \`${testCmd}\`
4. Open a pull request

---

_Generated by [create-allthing](https://github.com/your-org/create-allthing) · ${new Date().getFullYear()}_
`;
}
